version: "3.2"
services:
  crypto-bot:
    image: wuuker/python-bot-env:python3.9
    container_name: crypto-bot
    command: ["-u", "/app/get_data.py"]
    restart: unless-stopped
    volumes:
      - type: bind
        source: /container-data/crypto-bot
        target: /app
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
